### ISSUE TITLE
Question about how it work

### ISSUE THREAD

**Issue by santiagoworkana** [hanbrandon/hypertube#1]
Hello, I have a quick question.
Are the videos downloaded to the server and the server stream them, or the videos are downloaded directly by the fian client on their browser and play locally?
Thanks

**Comment by hanbrandon** [comment]
Hi,
In the manual, it says “Once the movie is entirely downloaded, it must be saved on the server, so that we don’t need to re-download the movie again. If a movie is unwatched for a month, it will have to be erased.”

Thanks

iOS용 Outlook<https://aka.ms/o0ukef> 다운로드
________________________________
보낸 사람: Santiago Nisnik <notifications@github.com>
보낸 날짜: Monday, September 30, 2019 6:19:19 AM
받는 사람: hanbrandon/hypertube <hypertube@noreply.github.com>
참조: Subscribed <subscribed@noreply.github.com>
제목: [hanbrandon/hypertube] Question about how it work (#1)


Hello, I have a quick question.
Are the videos downloaded to the server and the server stream them, or the videos are downloaded directly by the fian client on their browser and play locally?
Thanks

**Comment by santiagoworkana** [comment]
great! thanks!!
